
version: "3.9"
services:
  web:
    build: .
    ports:
      - "80:5000"
      - "5001:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=sqlite:///instance/catalog.db
