version: "3.9"
services:
  web:
    build: .
    command: gunicorn -w 2 --threads 1 -b 0.0.0.0:5000 --access-logfile - --error-logfile - wsgi:app
    ports:
      - "5001:5000"         # host:container
    volumes:
      - .:/app
      - ./instance:/app/instance