version: "3.9"

services:
  web:
    build: .
    image: current-web
    ports:
      - "80:5000"     # EB/public access
      - "5001:5000"   # local dev convenience: http://localhost:5001
    environment:
      - DATABASE_URL=sqlite:////app/instance/catalog.db
      - SECRET_KEY=dev
      - PORT=5000
    command: >
      gunicorn -w 4 -k sync -b 0.0.0.0:5000 wsgi:app
    restart: always