services:
  web:
    build: .
    command: gunicorn -w 1 -k sync -b 0.0.0.0:5000 wsgi:app
    ports:
      - "5001:5000"
    environment:
      - DATABASE_URL=sqlite:////app/instance/catalog.db
      - SECRET_KEY=dev
    volumes:
      - .:/app
      - ./instance:/app/instance