services:
  web:
    build: .
    image: current-web
    ports:
      - "80:5000"   # was "5001:5000"
    environment:
      - PORT=5000   # gunicorn binds to 5000 inside the container
      - DATABASE_URL=sqlite:////app/instance/catalog.db
      - SECRET_KEY=dev
    volumes:
      - .:/app
      - ./instance:/app/instance