AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: CAD4Less backend API

Globals:
  Function:
    Timeout: 30
    MemorySize: 256
    Runtime: nodejs18.x
    Architectures:
      - x86_64

Resources:

  #####################################################
  # API Gateway (REST API) with global CORS
  #####################################################

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: v1
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"

  #####################################################
  # Fetch Live Parts from DynamoDB
  #####################################################

  FetchPartsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      CodeUri: backend/fetchParts/
      Runtime: nodejs18.x
      Environment:
        Variables:
          PARTS_TABLE_NAME: Cad4LessPartsLive
      Policies:
        - DynamoDBReadPolicy:
            TableName: Cad4LessPartsLive
      Events:
        FetchParts:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /parts
            Method: GET

  #####################################################
  # Import Parts from Apify / CSV
  #####################################################

  ImportPartsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      CodeUri: backend/importParts/
      Runtime: nodejs18.x
      Environment:
        Variables:
          PARTS_TABLE_NAME: Cad4LessPartsLive
          APIFY_TOKEN: APIFY_TOKEN_PLACEHOLDER
      Policies:
        - DynamoDBCrudPolicy:
            TableName: Cad4LessPartsLive
      Events:
        ImportParts:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /parts/import
            Method: GET
        ImportPartsCsv:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /parts/import-csv
            Method: POST
        ImportPartsByCategory:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /imports/apify/{category}
            Method: POST

  #####################################################
  # External Parts Fetcher (Node 22)
  #####################################################

  FetchPartsExternalFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      CodeUri: backend/fetchPartsExternal/
      Runtime: nodejs22.x
      Environment:
        Variables:
          PARTS_TABLE_NAME: Cad4LessPartsLive
      Policies:
        - DynamoDBReadPolicy:
            TableName: Cad4LessPartsLive
      Events:
        FetchExternalParts:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /parts/external
            Method: GET

  #####################################################
  # Update / Approve Parts
  #####################################################

  ApprovePartFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      CodeUri: backend/ApprovePart/
      Runtime: nodejs16.x
      Environment:
        Variables:
          PARTS_TABLE_NAME: Cad4LessPartsLive
      Policies:
        - DynamoDBCrudPolicy:
            TableName: Cad4LessPartsLive
      Events:
        ApprovePart:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /parts/approved
            Method: POST
        ApprovePartPreflight:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /parts/approved
            Method: OPTIONS

  #####################################################
  # List Pending Parts
  #####################################################

  ListPendingPartsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      CodeUri: backend/listPendingParts/
      Runtime: nodejs18.x
      Environment:
        Variables:
          PARTS_TABLE_NAME: Cad4LessPartsLive
      Policies:
        - DynamoDBReadPolicy:
            TableName: Cad4LessPartsLive
      Events:
        ListPendingParts:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /parts/pending
            Method: GET

  #####################################################
  # Delete Part (soft delete)
  #####################################################

  DeletePartFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      CodeUri: backend/deletePart/
      Runtime: nodejs18.x
      Environment:
        Variables:
          PARTS_TABLE_NAME: Cad4LessPartsLive
      Policies:
        - DynamoDBCrudPolicy:
            TableName: Cad4LessPartsLive
      Events:
        DeletePart:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /parts/{id}
            Method: DELETE
        DeletePartPreflight:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /parts/{id}
            Method: OPTIONS
        DeletePartPost:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /parts/delete
            Method: POST

  #####################################################
  # PC Builds CRUD
  #####################################################

  PcBuildsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      CodeUri: backend/pcBuilds/
      Runtime: nodejs18.x
      Environment:
        Variables:
          BUILDS_TABLE_NAME: Cad4LessPcBuilds
      Policies:
        - DynamoDBCrudPolicy:
            TableName: Cad4LessPcBuilds
      Events:
        ListAndCreateBuilds:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /builds
            Method: ANY
        SingleBuildOperations:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /builds/{buildId}
            Method: ANY

  #####################################################
  # API Gateway Default GatewayResponses with CORS
  #####################################################

  ApiGatewayResponseDefault4XX:
    Type: AWS::ApiGateway::GatewayResponse
    Properties:
      RestApiId: !Ref ApiGateway
      ResponseType: DEFAULT_4XX
      StatusCode: '400'
      ResponseParameters:
        gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
        gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        gatewayresponse.header.Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"

  ApiGatewayResponseDefault5XX:
    Type: AWS::ApiGateway::GatewayResponse
    Properties:
      RestApiId: !Ref ApiGateway
      ResponseType: DEFAULT_5XX
      StatusCode: '500'
      ResponseParameters:
        gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
        gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        gatewayresponse.header.Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"

Outputs:
  ApiUrl:
    Description: Base URL for CAD4Less API
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/v1/"