# backend/template.yaml
#
# NOTE:
# This file is not used by the SAM build/deploy process.
# The actual SAM/CloudFormation template for the CAD4Less backend
# is located at the project root:
#
#   /Users/shobhon/Downloads/cad4less-catalog/template.yaml
#
# This placeholder exists only to avoid confusion when browsing
# the backend folder. All Lambda functions are defined and wired
# in the root template.yaml file.
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Unused backend-local SAM template placeholder'